export default [
 {
   "bill": "hr1370-115",
   "economy": true,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "s756-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": true,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN1095",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN48",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN44",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": true,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN42",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN43",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN40",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": true,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN41",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres36-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": true,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres66-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN696",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN1761",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "s2372-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr601-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr244-115",
   "economy": false,
   "immigration": true,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "sconres3-115",
   "economy": false,
   "immigration": true,
   "defense": true,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres37-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": true,
   "legal": false
 },
 {
   "bill": "hr695-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": true,
   "legal": false
 },
 {
   "bill": "hjres44-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": true,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN50",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN55",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "PN54",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres43-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "sjres42-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres58-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": true,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres38-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres111-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "hr1892-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-1-final1-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": true,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres42-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres57-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": true,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-senate-repeal1628-115",
   "economy": false,
   "immigration": true,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "s109-116",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN29",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN25",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN26",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "nuclear0-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": true,
   "legal": false
 },
 {
   "bill": "sjres2-116",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "PN1857",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "s84-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-conference2-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "s722-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "sjres52-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": true,
   "legal": false
 },
 {
   "bill": "PN39",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN37",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": true,
   "legal": false
 },
 {
   "bill": "PN36",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": true,
   "infrastructure": false,
   "science and technology": true,
   "legal": false
 },
 {
   "bill": "PN35",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN34",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN33",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN32",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN31",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "PN30",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "hjres41-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": true,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-1-senate1-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "hr-senate-amendment-5268-116",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": true,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hrsamd1958-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr195a-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN2179",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hrsamd1959-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr2266-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "sjres63-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "PN1371",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "sjres34-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": true,
   "legal": false
 },
 {
   "bill": "PN88",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres40-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres83-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "hr2-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": true,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hconres71-115",
   "economy": true,
   "immigration": true,
   "defense": true,
   "healthcare": true,
   "education": true,
   "environment": true,
   "infrastructure": true,
   "science and technology": true,
   "legal": true
 },
 {
   "bill": "sjres57-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-delay1628-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr3-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "hjres123-115",
   "economy": true,
   "immigration": true,
   "defense": true,
   "healthcare": true,
   "education": true,
   "environment": true,
   "infrastructure": true,
   "science and technology": true,
   "legal": true
 },
 {
   "bill": "sjres64-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "PN90",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "s2155-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-senate-amendment-6268-116",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "PN2259",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "hr1625-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr3364-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "s2311-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr195-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-tariffs5515-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr-mtp1628-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hjres67-115",
   "economy": true,
   "immigration": false,
   "defense": false,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "hr6-115",
   "economy": false,
   "immigration": false,
   "defense": false,
   "healthcare": true,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": true
 },
 {
   "bill": "sjres54-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 },
 {
   "bill": "s139-115",
   "economy": false,
   "immigration": false,
   "defense": true,
   "healthcare": false,
   "education": false,
   "environment": false,
   "infrastructure": false,
   "science and technology": false,
   "legal": false
 }
]